### ISSUE TITLE
toNumber typing requires the decimals parameter

### ISSUE THREAD

**Issue by nbran** [bpierre/dnum#12]
First of all, thanks for working on this library, it's incredibly useful and well designed. 

The docs seem to state that the number of digits is optional for the `toNumber` utility:

> _Defaults to the number of decimals in the Dnum passed to value._

However, TS will complain if/when only the Dnum is passed. This doesn't happen with the options for other utilities (e.g., `format`).

**Comment by bpierre** [comment]
Fixed and released! https://github.com/bpierre/dnum/releases/tag/v2.12.0

Thanks for reporting the issue and for the kind words @nbran! :pray: :heart:
