### ISSUE TITLE
Types not supported  Node16+ module resolution

### ISSUE THREAD

**Issue by ryangoree** [bpierre/dnum#7]
The type definitions in the build use relative import paths that don't include the extensions. This means projects using `Node16` or `NodeNext` [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) in their typescript projects won't be able to resolve the types.

- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html
- https://nodejs.org/api/esm.html#mandatory-file-extensions

<img width="480" alt="image" src="https://github.com/bpierre/dnum/assets/3289505/6daebfb0-c7e1-49e1-b154-a14dbe5752a0">

**Comment by bpierre** [comment]
Done in https://github.com/bpierre/dnum/commit/55ae3069df3cbd7909e498fe212278852f9a72d9

The types are now bundled in a single file: https://unpkg.com/browse/dnum@2.10.0/dist/index.d.ts

@ryangoree :pray:
